# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit inflateR.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----directions---------------------------------------------------------------
directions <- data.frame(
  Direction = c("Historical to present", "Present to historical"),
  CPI = c("adjust_inflation()", "historical_value()"),
  Deflator = c("adjust_real()", "historical_real()")
)
knitr::kable(directions,
             col.names = c("Direction", "CPI measure", "GDP deflator measure"),
             caption = "The four value-conversion functions in inflateR, arranged by direction and inflation measure.",
             booktabs = TRUE)


## ----currencies---------------------------------------------------------------
currencies <- data.frame(
  Currency = c("GBP", "AUD", "USD", "EUR", "CAD", "JPY", "CNY",
               "CHF", "NZD", "INR", "KRW", "BRL", "NOK"),
  Country = c("United Kingdom", "Australia", "United States",
              "Euro area (Germany proxy)", "Canada", "Japan",
              "China", "Switzerland", "New Zealand", "India",
              "South Korea", "Brazil", "Norway"),
  Start = c(1960L, 1960L, 1960L, 1960L, 1960L, 1960L, 1986L,
            1960L, 1960L, 1960L, 1960L, 1980L, 1960L),
  End = rep(2024L, 13)
)
knitr::kable(currencies,
             col.names = c("Currency", "Country", "CPI start", "CPI end"),
             caption = "The thirteen currencies supported by inflateR, with the first and last years of CPI coverage. All series come from the World Bank Development Indicators and are rescaled to a common base year of 2020 = 100.",
             booktabs = TRUE)


## ----coverage, fig.cap = "CPI coverage by currency and decade in the bundled \\texttt{inflateR} data. Blue tiles mark decades with at least one year of coverage; grey tiles mark absence. Eleven of the thirteen currencies are covered from 1960 onwards; CNY coverage begins 1986 and BRL coverage begins 1980.", fig.alt = "A heatmap with thirteen currency rows and seven decade columns from the 1960s to the 2020s. Most cells are shaded blue, indicating coverage. Grey cells appear for CNY in the 1960s and 1970s, and for BRL in the 1960s and 1970s, showing the later start dates for those two currencies."----
knitr::include_graphics("figures/fig4_coverage.pdf")


## ----multipliers, fig.cap = "CPI-based inflation multiplier to 2024 for five currencies, 1970 to 2024. Log-scale y-axis: a value of 10x means one unit of that year's currency has the same purchasing power as 10 units in 2024. The 1970s are the steepest decade for GBP, USD, AUD, and EUR; JPY is notably flatter, consistent with Japan's lower and later-stage inflation history.", fig.alt = "A line chart on a log-scale y-axis showing inflation multipliers to 2024 for GBP, USD, AUD, EUR, and JPY from 1970 to 2024. The multipliers start around ten to fifteen in 1970 and decline monotonically toward one by 2024. JPY is notably flatter than the others over the post-2000 period."----
knitr::include_graphics("figures/fig1_multipliers.pdf")


## ----rolling, fig.cap = "Rolling 10-year annualised inflation rate across five currencies, 1970 to 2014 (start year). Dashed horizontal line at 2 per cent is the modern inflation-target norm. The late-1970s peak is visible for GBP, USD, AUD, and EUR; the mid-2000s trough (including near-zero inflation in some economies) is the global-disinflation period.", fig.alt = "A line chart showing rolling 10-year annualised CPI inflation rates for GBP, USD, AUD, EUR, and JPY, plotted by start year from 1970 to 2014. A dashed horizontal line sits at 2 per cent. Most lines peak in the late 1970s between 8 and 12 per cent, converge toward 2 per cent through the 1990s and 2000s, and show a small uptick at the right edge."----
knitr::include_graphics("figures/fig2_rolling.pdf")


## ----cpi-gdp, fig.cap = "CPI and GDP deflator multipliers for GBP, 1970 to 2024, both to the 2024 base. Log-scale y-axis. The two measures diverge most in high-inflation periods (the 1970s and early 1980s) and in energy- and import-sensitive episodes (the post-2020 spike). Using CPI for a wages question and the GDP deflator for a government-spending question is the intended match.", fig.alt = "A line chart on a log-scale y-axis comparing the GBP CPI-based multiplier and the GBP GDP deflator multiplier to 2024, from 1970 onwards. Both lines fall from around fifteen in 1970 to one by 2024. The two series track each other closely but diverge visibly in the 1970s, early 1980s, and after 2020."----
knitr::include_graphics("figures/fig3_cpi_gdp.pdf")


## ----power, fig.cap = "Purchasing power of 1 unit of GBP, USD, and JPY relative to 1970, 1970 to 2024. Computed via \\texttt{1 / adjust\\_inflation(1, 1970, ccy, to\\_year = y)}. GBP and USD each lose the bulk of their 1970 purchasing power; JPY loses less, reflecting its lower average inflation over the period.", fig.alt = "A line chart showing the purchasing power of 1 unit of GBP, USD, and JPY in 1970 terms, plotted annually from 1970 to 2024. All three lines start at 1.0 in 1970 and decline monotonically. GBP reaches about 0.07 by 2024, USD about 0.13, and JPY about 0.30."----
knitr::include_graphics("figures/fig5_power.pdf")


## ----uk-wages, fig.cap = "UK median weekly earnings, nominal and real (2024 GBP), 1980 to 2024. Data: Office for National Statistics Annual Survey of Hours and Earnings, median gross weekly pay for full-time employees. Grey dashed: nominal GBP (as published). Blue solid: real GBP, deflated by \\texttt{adjust\\_inflation()} using World Bank CPI. Real median weekly earnings rose steadily from GBP 533 in 1980 to a peak of GBP 721 in 2010 (plus 35 per cent), then fell back to GBP 681 by 2024 (minus 5.6 per cent post-2010).", fig.alt = "A line chart of UK median full-time weekly earnings from 1980 to 2024. A grey dashed line shows nominal pounds, rising steadily from under 100 pounds in 1980 to around 700 pounds in 2024. A blue solid line shows real pounds in 2024 terms, rising from about 533 pounds in 1980, peaking around 721 pounds near 2010, then declining gradually to 681 pounds by 2024."----
knitr::include_graphics("figures/fig6_uk_wages.pdf")

